#!/bin/sh

uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server='0.cn.pool.ntp.org'
	add_list system.ntp.server='1.cn.pool.ntp.org'
	add_list system.ntp.server='2.cn.pool.ntp.org'
	add_list system.ntp.server='3.cn.pool.ntp.org'
EOF
uci commit system

sed -i 's,downloads.openwrt.org,mirrors.tencent.com/openwrt,g' /etc/opkg/distfeeds.conf
sed -i 's,downloads.openwrt.org,mirrors.vsean.net/openwrt,g' /etc/opkg/distfeeds.conf

exit 0
